# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/tfu_tanh_purelut_8_19/tfu_tanh_purelut_8_19.xci
# IP: The module: 'tfu_tanh_purelut_8_19' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/tfu_tanh_purelut_8_19/src/lut_intercept_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tfu_tanh_purelut_8_19'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/tfu_tanh_purelut_8_19/src/lut_slope_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tfu_tanh_purelut_8_19'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/tfu_tanh_purelut_8_19/tfu_tanh_purelut_8_19.xci
# IP: The module: 'tfu_tanh_purelut_8_19' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/tfu_tanh_purelut_8_19/src/lut_intercept_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tfu_tanh_purelut_8_19'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/tfu_tanh_purelut_8_19/src/lut_slope_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tfu_tanh_purelut_8_19'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
