#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.3 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Nov 17 00:19:29 EST 2021
# SW Build 2644227 on Wed Sep  4 09:44:18 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto cd2c85c5e4674887b108c5edb371c54f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot esn_core_sdrtb_func_synth xil_defaultlib.esn_core_sdrtb xil_defaultlib.glbl -log elaborate.log"
xelab -wto cd2c85c5e4674887b108c5edb371c54f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L secureip --snapshot esn_core_sdrtb_func_synth xil_defaultlib.esn_core_sdrtb xil_defaultlib.glbl -log elaborate.log

