# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/eth_sgmii/eth_sgmii.xci
# IP: The module: 'eth_sgmii' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/eth_sgmii/eth_sgmii_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_sgmii'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/eth_sgmii/synth/eth_sgmii.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_sgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/eth_sgmii/synth/eth_sgmii_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_sgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/eth_sgmii/eth_sgmii.xci
# IP: The module: 'eth_sgmii' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/eth_sgmii/eth_sgmii_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_sgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/eth_sgmii/synth/eth_sgmii.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_sgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/eth_sgmii/synth/eth_sgmii_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'eth_sgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
