# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/dsp48_macro_typeB/dsp48_macro_typeB.xci
# IP: The module: 'dsp48_macro_typeB' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/dsp48_macro_typeB/dsp48_macro_typeB_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp48_macro_typeB'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/dsp48_macro_typeB/dsp48_macro_typeB.xci
# IP: The module: 'dsp48_macro_typeB' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sources_1/ip/dsp48_macro_typeB/dsp48_macro_typeB_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp48_macro_typeB'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
