@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue May 30 12:49:37 -0400 2023
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim esn_core_sdrtb_behav -key {Behavioral:sim_1:Functional:esn_core_sdrtb} -tclbatch esn_core_sdrtb.tcl -view C:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sim_1/imports/digitalesn.sim/esn_core_sdrtb_behav.wcfg -log simulate.log"
call xsim  esn_core_sdrtb_behav -key {Behavioral:sim_1:Functional:esn_core_sdrtb} -tclbatch esn_core_sdrtb.tcl -view C:/Users/azmin/Desktop/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sim_1/imports/digitalesn.sim/esn_core_sdrtb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
