#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Dec 10 15:25:30 EST 2022
# SW Build 2644227 on Wed Sep  4 09:44:18 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim esn_core_sdrtb_behav -key {Behavioral:sim_1:Functional:esn_core_sdrtb} -tclbatch esn_core_sdrtb.tcl -view /home/chunxiao/Documents/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sim_1/imports/digitalesn.sim/esn_core_sdrtb_behav.wcfg -log simulate.log"
xsim esn_core_sdrtb_behav -key {Behavioral:sim_1:Functional:esn_core_sdrtb} -tclbatch esn_core_sdrtb.tcl -view /home/chunxiao/Documents/ESN_MIMO/ESN_MIMO_e3/ESN_MIMO_e3.srcs/sim_1/imports/digitalesn.sim/esn_core_sdrtb_behav.wcfg -log simulate.log

